version: '2'
services:
  python:
    image: cithub/tensorflow
    container_name: python
    environment:
      - PASSWORD=password
    volumes:
      - ./data/tensorflow:/data
    ports:
      - 6006:6006
      - 8888:8888
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=discoverer
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    container_name: kibana
    volumes:
      - ./data/kibana/data:/usr/share/kibana/data
      - ./data/kibana/logs:/usr/share/kibana/logs
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic: